const fs = require('fs');
const path = require('path');

const deDict = {
  "Desired Service": "Gewünschte Dienstleistung",
  "Cleaning Only": "Nur Reinigung",
  "Moving And Cleaning": "Umzug und Reinigung",
  "Cleaning Location": "Reinigungsort",
  "Object Type": "Objektart",
  "Apartment": "Wohnung",
  "House": "Haus",
  "Wg Room": "WG-Zimmer",
  "Office": "Büro",
  "Storage Cellar": "Lager / Keller",
  "Contact": "Kontakt",
  "Name Company": "Name / Firma",
  "Contact Person": "Ansprechperson",
  "Phone": "Telefon",
  "Email": "E-Mail",
  "Property": "Objekt",
  "Address / Street *": "Adresse / Strasse *",
  "Area (m²)": "Fläche (m²)",
  "Rooms": "Zimmer",
  "Sanitary": "Sanitäre Anlagen",
  "Usage": "Nutzung",
  "Private": "Privat",
  "Commercial": "Geschäftlich",
  "High Traffic": "Stark frequentiert",
  "Floor Types": "Bodenarten",
  "Scope Of Services": "Leistungsumfang",
  "Vacuuming": "Staubsaugen",
  "Wet Mopping": "Nass aufnehmen",
  "Dusting": "Abstauben",
  "Kitchen": "Küche",
  "Offices Rooms": "Büros / Zimmer",
  "Windows": "Fenster",
  "Stairwell": "Treppenhaus",
  "Waste": "Abfall",
  "Frequency": "Häufigkeit",
  "Daily": "Täglich",
  "Two Three Times": "Zwei- bis dreimal",
  "Weekly": "Wöchentlich",
  "Biweekly": "Alle zwei Wochen",
  "Monthly": "Monatlich",
  "Custom": "Individuell",
  "Service Times": "Einsatzzeiten",
  "Early Morning": "Frühmorgens",
  "Morning": "Morgens",
  "Afternoon": "Nachmittags",
  "Evening": "Abends",
  "During operation": "Während Betrieb",
  "After operation": "Nach Betrieb",
  "Flexible": "Flexibel",
  "Cleaning Duration": "Reinigungsdauer",
  "Hours12": "1-2 Stunden",
  "Hours23": "2-3 Stunden",
  "Hours35": "3-5 Stunden",
  "Half Day": "Halber Tag",
  "Full day": "Ganzer Tag",
  "Start & Planning": "Start & Planung",
  "Start Date": "Startdatum",
  "Org And Access": "Organisation & Zugang",
  "Key available": "Schlüssel vorhanden",
  "Code / system": "Code / System",
  "Client on site": "Kunde vor Ort",
  "Special": "Spezielles",
  "Pets": "Haustiere",
  "Children": "Kinder",
  "Alarm System": "Alarmanlage",
  "Additional Services": "Zusätzliche Dienstleistungen",
  "Disinfection": "Desinfektion",
  "Deep cleaning": "Grundreinigung",
  "Special cleaning": "Spezialreinigung",
  "Upload": "Hochladen",
  "Photos": "Fotos",
  "Documents": "Dokumente",
  "Notes": "Bemerkungen",
  
  "Company Or Management": "Firma oder Verwaltung",
  "Property Type": "Objekttyp",
  "Apartment Building": "Mehrfamilienhaus",
  "Commercial Property": "Gewerbeimmobilie",
  "Residential Complex": "Wohnanlage",
  "Office Building": "Bürogebäude",
  "Units": "Einheiten",
  "Cleaning Maintenance": "Unterhaltsreinigung",
  "Elevator": "Aufzug",
  "Garage": "Garage",
  "Basement": "Keller",
  "Outdoor Maintenance": "Aussenpflege",
  "Landscaping": "Gartenpflege",
  "Outdoor Cleaning": "Aussenreinigung",
  "Parking": "Parkplätze",
  "Snow Removal": "Schneeräumung",
  "Gritting Service": "Winterdienst (Streuen)",
  "Tech Inspections": "Technische Inspektionen",
  "Routine Checks": "Routiniekontrollen",
  "Minor Repairs": "Kleinere Reparaturen",
  "Lighting Checks": "Beleuchtungskontrollen",
  "Waste Handling": "Abfallbewirtschaftung",
  "Container Cleaning": "Containerreinigung",
  "Disposal Recycling": "Entsorgung & Recycling",
  "Outdoor Surroundings": "Umgebungspflege",
  "Winter Service": "Winterdienst",
  "Technical Maintenance": "Technische Wartung",
  "Waste Management": "Abfallmanagement",
  "Property Details": "Objektdetails",
  "Staircases": "Treppenhäuser",
  "Elevators": "Aufzüge",
  "Entrances": "Eingänge",
  "Parking Spaces": "Parkplätze",
  "Special Reqs": "Spezielle Anforderungen",
  "House Rules": "Hausordnung",
  "Contact On Site": "Kontakt vor Ort",
  "Service Specs": "Service-Spezifikationen",
  "Access": "Zugang",
  "Free": "Frei",
  "Key": "Schlüssel",
  "Code": "Code",
  "Daytime": "Tagsüber",
  "Desired Start": "Gewünschter Start",
  "Contract Type": "Vertragsart",
  "Ongoing": "Laufend",
  "Trial": "Probezeit",
  "One Time": "Einmalig",
  "Emergency": "Notfall",
  "Availability24h": "24h Verfügbarkeit",
  "Reports": "Berichte",
  "Photo Doc": "Fotodokumentation",
  
  "Layout": "Aufteilung",
  "Bedrooms": "Schlafzimmer",
  "Bathrooms": "Badezimmer",
  "Separate Wc": "Separates WC",
  "Kitchens": "Küchen",
  "Shower": "Dusche",
  "Bathtub": "Badewanne",
  "Double Sink": "Doppellavabo",
  "Guest Wc": "Gäste-WC",
  "Glass Shower Wall": "Glas-Duschwand",
  "Mirrors": "Spiegel",
  "Fittings": "Armaturen",
  "Oven": "Backofen",
  "Cooktop": "Kompaktkreislauf",
  "Refrigerator": "Kühlschrank",
  "Freezer": "Gefrierschrank",
  "Dishwasher": "Geschirrspüler",
  "Extractor Hood": "Dunstabzugshaube",
  "Cabinets inside": "Schränke innen",
  "Cabinets outside": "Schränke aussen",
  "Work surfaces": "Arbeitsflächen",
  "Laundry Room": "Waschküche",
  "Clean washing machine": "Waschmaschine reinigen",
  "Clean dryer": "Tumbler / Trockner reinigen",
  "Location": "Standort",
  "Shared room": "Gemeinschaftsraum",
  "Additional Rooms & Outdoor Areas": "Zusätzliche Räume & Aussenbereiche",
  "Balcony": "Balkon",
  "Terrace": "Terrasse",
  "Machine": "Maschinell",
  "Manual": "Manuell",
  "Other Rooms": "Andere Zimmer",
  "Attic": "Dachboden",
  "Storage Room": "Abstellraum",
  "Windows & Shading": "Fenster & Storen",
  "Windows Info": "Fenster Informationen",
  "Standard": "Standard",
  "Floor To Ceiling": "Bodeneben",
  "Roof Windows": "Dachfenster",
  "Large Surfaces": "Grosse Fensterflächen",
  "Hard To Access": "Schwer zugänglich",
  "Shading": "Storen / Beschattung",
  "Venetian": "Lamellenstoren",
  "Roller Shutters": "Rollladen",
  "Window Shutters": "Fensterläden",
  "Parquet": "Parkett",
  "Laminate": "Laminat",
  "Tiles": "Fliesen",
  "Stone": "Stein / Platten",
  "Carpet": "Teppich",
  "Pvc": "PVC / Vinyl",
  "Cleaning Scope": "Reinigungsumfang",
  "Full (handover standard)": "Komplett (Abgabestandard)",
  "General": "Allgemein",
  "Floors": "Böden",
  "Doors": "Türen",
  "Frames": "Rahmen",
  "Cabinets": "Schränke",
  "Sockets": "Steckdosen",
  "Light switches": "Lichtschalter",
  "Limescale removal": "Kalkentfernung",
  "Grout cleaning": "Fugenreinigung",
  "Descaling": "Entkalken",
  "Condition": "Zustand",
  "Normal": "Normal",
  "Heavily Soiled": "Stark verschmutzt",
  "Nicotine": "Nikotin",
  "Construction": "Baustelle",
  "Handover Management": "Übergabemanagement",
  "Handover Date": "Übergabedatum",
  "Inspection": "Abnahme",
  "Guarantee": "Garantie",
  "Management Contact": "Kontakt Verwaltung",
  "Access & Logistics": "Zugang & Logistik",
  "Floor": "Etage",
  "Small": "Klein",
  "Medium": "Mittel",
  "Large": "Gross",
  "Parking": "Parkplatz",
  "Reserved": "Reserviert",
  "Distance parking \u2192 entrance (m)": "Entfernung Parkplatz \u2192 Eingang (m)",
  "Possible": "Möglich",
  "Restricted": "Eingeschränkt",
  "Key Handover": "Schlüsselübergabe",
  "In Person": "Persönlich",
  "Mailbox": "Briefkasten",
  "Neighbor": "Nachbar",
  "Management": "Verwaltung",
  "Key Box": "Schlüsselkasten",
  "Schedule": "Zeitplan",
  "Cleaning Date": "Reinigungsdatum",
  "From *": "Von *",
  "To *": "Bis *",
  "Express": "Express",
  "Re-cleaning after inspection": "Nachreinigung nach Abnahme",
  "Guarantee until handover": "Garantie bis zur Übergabe",
  "Disposal": "Entsorgung",
  "Moving combined": "Umzugskombination",
  
  "Industrial": "Industrie",
  "Public": "Öffentlich",
  "Concrete": "Beton",
  "Epoxy": "Epoxid",
  "Rough": "Grob",
  "Fine": "Fein",
  "Intermediate": "Zwischenreinigung",
  "Handover": "Übergabe",
  "Project": "Projekt",
  "Project Phase": "Projektphase",
  "Phase": "Phase",
  "Skylights": "Oberlichter",
  "Facade": "Fassade",
  "Paint Spoils": "Farbspritzer",
  "Stickers": "Aufkleber / Folien",
  "Cement": "Zement",
  "Glue": "Kleber",
  "Dust": "Staub",
  "Silicone": "Silikon",
  "Waste Disposal": "Abfallentsorgung",
  "Container": "Container",
  "High Pressure": "Hochdruckreinigung",
  "Sealing": "Versiegelung",
  "On Site Context": "Vor Ort Gegebenheiten",
  "Water": "Wasser",
  "Electricity": "Strom",
  "Deadline": "Frist",
  "Name Contact": "Name Kontakt",
  
  "Hotel": "Hotel",
  "Canteen": "Kantine",
  "Catering": "Gastronomie",
  "Take-away": "Take-away",
  "Cafe": "Café",
  "Bar": "Bar",
  "Takeaway": "Takeaway",
  "Club": "Club",
  "Restrooms": "Toiletten",
  "Staff Restrooms": "Personaltoiletten",
  "Kitchen Details": "Küchendetails",
  "Grease Traps": "Fettabscheider",
  "Ovens": "Öfen",
  "Deep Fryers": "Fritteusen",
  "Cooling Units": "Kühlanlagen",
  "Drains": "Abflüsse",
  "Walls": "Wände",
  "Dining Details": "Essbereich Details",
  "Seating": "Sitzplätze",
  "Restroom Details": "Toiletten Details",
  "Urinals": "Urinale",
  "Stalls": "Kabinen",
  "Sinks": "Lavabos",
  "Requirements": "Anforderungen",
  "Night": "Nachts",
  "Current Property": "Aktuelle Immobilie",
  "Elevator Size": "Aufzugsgrösse",
  "New Property": "Neue Immobilie",
  "Property Size": "Immobiliengrösse",
  "Floor Area": "Nutzfläche",
  "Distance Parking": "Entfernung Parken",
  "Distance Details": "Distanzdetails",
  "Carrying Distance": "Tragdistanz",
  "Stairs Info": "Treppen Info",
  "Inventory": "Inventar",
  "Boxes": "Boxen",
  "Furniture Details": "Möbeldetails",
  "Heavy Items": "Schwere Gegenstände",
  "Assembly Needed": "Montage nötig",
  "Pianos": "Klavier / Flügel",
  "Safes": "Tresore",
  "Special Care": "Spezielle Sorgfalt",
  "Moving Details": "Umzugsdetails",
  "Move Date": "Umzugsdatum",
  "Move Time": "Umzugszeit",
  "Flexibility": "Flexibilität",
  "Timeframe": "Zeitrahmen",
  "Additional Needs": "Zusätzliche Bedürfnisse",
  "Packing Services": "Verpackungsservice",
  "Unpacking Services": "Auspackservice",
  "Storage Needed": "Lagerung benötigt",
  "Special Requests": "Spezielle Anfragen",

  // New keys for Services Selection
  "Disposal Type": "Entsorgungsart",
  "Household Goods": "Haushaltswaren",
  "Furniture": "Möbel",
  "Appliances": "Geräte",
  "Electronics": "Elektronik",
  "Green Waste": "Grünabfall",
  "Items & Volume": "Gegenstände & Volumen",
  "Location Type": "Standortart",
  "Additional Options": "Zusätzliche Optionen",
  "Dismantling needed": "Demontage nötig",
  "Container provided": "Container gestellt",

  "Windows Title": "Fenster & Glasbruch",
  "Normal Windows": "Normale Fenster (Anzahl / m²)",
  "French Doors": "Fenstertüren / Balkontüren",
  "Other Glass Surfaces": "Sonstige Glasflächen (Spiegel, etc.)",
  "Panoramic Hint": "Panoramaglas / Wintergarten",
  "Blinds Title": "Storen / Beschattung",
  "Shutters": "Fensterläden",
  "Slat": "Raffstoren",
  "Adjustable": "Verstellbare Storen",
  "Blinds": "Jalousien / Rollläden",
  "Other Special": "Sonstiges (Bitte angeben)",
  "No": "Nein",
  "Special Features Title": "Besonderheiten Fenster / Rahmen",
  "Mold Frames": "Schimmel am Rahmen",
  "Small Casement": "Viele kleine Sprossen",
  "Roof Window": "Dachfenster (schwer zugänglich)",
  "Safety Film": "Sicherheits- / Sonnenschutzfolien",
  "No Special": "Keine Besonderheiten",
  "Desired Cleaning Date": "Gewünschtes Reinigungsdatum",
  "Delivery Handover Date": "Geplantes Abgabedatum",
  "Moving From": "Auszugsadresse",
  "Current Living": "Aktuelle Wohnsituation",
  "Studio": "Studio / 1-Zimmer",
  "Elevator Available": "Aufzug vorhanden?",
  "Yes": "Ja",
  "Current Living Space": "Aktuelle Wohnfläche (m²)",
  "Moving To": "Einzugsadresse",
  "Storage": "Lager / Zwischenlagerung",
  "New Elevator": "Aufzug am neuen Ort?",
  "New Living Space": "Neue Wohnfläche (m²)",
  "People Moving": "Personen im Haushalt",
  "People Moving Hint": "Anzahl",
  "Moving Boxes": "Umzugskartons (Schätzung)",
  "Moving Boxes Hint": "Anzahl Kartons",
  "Additional Supplies Title": "Zusätzliches Verpackungsmaterial benötigt?",
  "Moving Box": "Standard Umzugskarton",
  "Wardrobe Box": "Kleiderbox",
  "Bottle Carton": "Gläser-/Flaschenkarton",
  "Adhesive Tape": "Klebeband",
  "Cellar": "Keller",
  "Attic Screed": "Estrich / Dachboden",
  "Garage Parking Space": "Garage / Parkplatz",
  "Conservatory Balcony": "Wintergarten / Balkon",
  "Stairs": "Treppenhaus",
  "Corridor": "Korridor / Flur",
  "Preferred Move Date": "Bevorzugtes Umzugsdatum",
  "Name First Name": "Name & Vorname",
  "Company": "Firma",
  "Telephone Number": "Telefonnummer",
  "Parking Distance": "Distanz zum Parkplatz",

  "Label": "Häufigkeit / Intervall",
  "Unique": "Einmalig",
  "Every Other Week": "Alle 14 Tage",
  "Several Times Week": "Mehrmals wöchentlich"
};

const frDict = {
  ...deDict,
  "Desired Service": "Service souhaité",
  "Cleaning Only": "Nettoyage uniquement",
  "Moving And Cleaning": "Déménagement et nettoyage",
  "Cleaning Location": "Lieu de nettoyage",
  "Object Type": "Type de bien",
  "Apartment": "Appartement",
  "House": "Maison",
  "Wg Room": "Chambre en colocation",
  "Office": "Bureau",
  "Storage Cellar": "Cave / Stockage",
  "Contact": "Contact",
  "Name Company": "Nom / Entreprise",
  "Contact Person": "Personne de contact",
  "Phone": "Téléphone",
  "Email": "E-mail",
  "Property": "Propriété",
  "Address / Street *": "Adresse / Rue *",
  "Area (m²)": "Surface (m²)",
  "Rooms": "Pièces",
  "Sanitary": "Sanitaires",
  "Usage": "Utilisation",
  "Private": "Privé",
  "Commercial": "Commercial",
  "High Traffic": "Très fréquenté",
  "Floor Types": "Types de sol",
  "Scope Of Services": "Étendue des prestations",
  "Vacuuming": "Passer l'aspirateur",
  "Wet Mopping": "Lavage humide",
  "Dusting": "Dépoussiérage",
  "Kitchen": "Cuisine",
  "Offices Rooms": "Bureaux / Pièces",
  "Windows": "Fenêtres",
  "Stairwell": "Cage d'escalier",
  "Waste": "Déchets",
  "Frequency": "Fréquence",
  "Daily": "Quotidien",
  "Two Three Times": "Deux à trois fois",
  "Weekly": "Hebdomadaire",
  "Biweekly": "Toutes les deux semaines",
  "Monthly": "Mensuel",
  "Custom": "Personnalisé",
  "Service Times": "Heures de service",
  "Early Morning": "Tôt le matin",
  "Morning": "Matin",
  "Afternoon": "Après-midi",
  "Evening": "Soir",
  "During operation": "Pendant l'ouverture",
  "After operation": "Après l'ouverture",
  "Flexible": "Flexible",
  "Cleaning Duration": "Durée du nettoyage",
  "Hours12": "1-2 heures",
  "Hours23": "2-3 heures",
  "Hours35": "3-5 heures",
  "Half Day": "Demi-journée",
  "Full day": "Journée entière",
  "Start & Planning": "Début & Planification",
  "Start Date": "Date de début",
  "Org And Access": "Organisation & Accès",
  "Key available": "Clé disponible",
  "Code / system": "Code / Système",
  "Client on site": "Client sur place",
  "Special": "Spécial",
  "Pets": "Animaux de compagnie",
  "Children": "Enfants",
  "Alarm System": "Système d'alarme",
  "Additional Services": "Services supplémentaires",
  "Disinfection": "Désinfection",
  "Deep cleaning": "Nettoyage en profondeur",
  "Special cleaning": "Nettoyage spécial",
  "Upload": "Télécharger",
  "Photos": "Photos",
  "Documents": "Documents",
  "Notes": "Remarques",
  
  "Company Or Management": "Entreprise ou Gérance",
  "Property Type": "Type de propriété",
  "Apartment Building": "Immeuble d'habitation",
  "Commercial Property": "Propriété commerciale",
  "Residential Complex": "Complexe résidentiel",
  "Office Building": "Immeuble de bureaux",
  "Units": "Unités",
  "Cleaning Maintenance": "Entretien ménager",
  "Elevator": "Ascenseur",
  "Garage": "Garage",
  "Basement": "Sous-sol",
  "Outdoor Maintenance": "Entretien extérieur",
  "Landscaping": "Aménagement paysager",
  "Outdoor Cleaning": "Nettoyage extérieur",
  "Parking": "Parking",
  "Snow Removal": "Déneigement",
  "Gritting Service": "Service de salage",
  "Tech Inspections": "Inspections techniques",
  "Routine Checks": "Contrôles de routine",
  "Minor Repairs": "Petites réparations",
  "Lighting Checks": "Contrôle d'éclairage",
  "Waste Handling": "Gestion des déchets",
  "Container Cleaning": "Nettoyage des conteneurs",
  "Disposal Recycling": "Élimination & Recyclage",
  "Outdoor Surroundings": "Aménagement extérieur",
  "Winter Service": "Service d'hiver",
  "Technical Maintenance": "Maintenance technique",
  "Waste Management": "Gestion des déchets",
  "Property Details": "Détails de la propriété",
  "Staircases": "Cages d'escalier",
  "Elevators": "Ascenseurs",
  "Entrances": "Entrées",
  "Parking Spaces": "Places de parking",
  "Special Reqs": "Exigences particulières",
  "House Rules": "Règlement intérieur",
  "Contact On Site": "Contact sur place",
  "Service Specs": "Spécifications du service",
  "Access": "Accès",
  "Free": "Libre",
  "Key": "Clé",
  "Code": "Code",
  "Daytime": "En journée",
  "Desired Start": "Début souhaité",
  "Contract Type": "Type de contrat",
  "Ongoing": "En cours",
  "Trial": "Période d'essai",
  "One Time": "Une fois",
  "Emergency": "Urgence",
  "Availability24h": "Disponibilité 24h/24",
  "Reports": "Rapports",
  "Photo Doc": "Documentation photo",
  
  "Layout": "Disposition",
  "Bedrooms": "Chambres à coucher",
  "Bathrooms": "Salles de bain",
  "Separate Wc": "WC séparé",
  "Kitchens": "Cuisines",
  "Shower": "Douche",
  "Bathtub": "Baignoire",
  "Double Sink": "Double vasque",
  "Guest Wc": "WC visiteurs",
  "Glass Shower Wall": "Paroi de douche en verre",
  "Mirrors": "Miroirs",
  "Fittings": "Robinetterie",
  "Oven": "Four",
  "Cooktop": "Plaque de cuisson",
  "Refrigerator": "Réfrigérateur",
  "Freezer": "Congélateur",
  "Dishwasher": "Lave-vaisselle",
  "Extractor Hood": "Hotte aspirante",
  "Cabinets inside": "Armoires (intérieur)",
  "Cabinets outside": "Armoires (extérieur)",
  "Work surfaces": "Plans de travail",
  "Laundry Room": "Buanderie",
  "Clean washing machine": "Nettoyer le lave-linge",
  "Clean dryer": "Nettoyer le sèche-linge",
  "Location": "Emplacement",
  "Shared room": "Pièce commune",
  "Additional Rooms & Outdoor Areas": "Pièces supplémentaires & Extérieurs",
  "Balcony": "Balcon",
  "Terrace": "Terrasse",
  "Machine": "Machine",
  "Manual": "Manuel",
  "Other Rooms": "Autres pièces",
  "Attic": "Grenier",
  "Storage Room": "Cellier",
  "Windows & Shading": "Fenêtres & Stores",
  "Windows Info": "Infos fenêtres",
  "Standard": "Standard",
  "Floor To Ceiling": "Du sol au plafond",
  "Roof Windows": "Fenêtres de toit",
  "Large Surfaces": "Grandes surfaces vitrées",
  "Hard To Access": "Difficile d'accès",
  "Shading": "Ombrage",
  "Venetian": "Stores vénitiens",
  "Roller Shutters": "Volets roulants",
  "Window Shutters": "Volets battants",
  "Parquet": "Parquet",
  "Laminate": "Stratifié",
  "Tiles": "Carrelage",
  "Stone": "Pierre",
  "Carpet": "Moquette",
  "Pvc": "PVC / Vinyle",
  "Cleaning Scope": "Étendue du nettoyage",
  "Full (handover standard)": "Complet (standard remise)",
  "General": "Général",
  "Floors": "Sols",
  "Doors": "Portes",
  "Frames": "Cadres",
  "Cabinets": "Armoires",
  "Sockets": "Prises de courant",
  "Light switches": "Interrupteurs",
  "Limescale removal": "Détartrage",
  "Grout cleaning": "Nettoyage des joints",
  "Descaling": "Détartrage",
  "Condition": "État",
  "Normal": "Normal",
  "Heavily Soiled": "Très sale",
  "Nicotine": "Nicotine",
  "Construction": "Chantier",
  "Handover Management": "Gestion de la remise",
  "Handover Date": "Date de remise",
  "Inspection": "Inspection",
  "Guarantee": "Garantie",
  "Management Contact": "Contact de la gérance",
  "Access & Logistics": "Accès & Logistique",
  "Floor": "Étage",
  "Small": "Petit",
  "Medium": "Moyen",
  "Large": "Grand",
  "Reserved": "Réservé",
  "Distance parking \u2192 entrance (m)": "Distance parking \u2192 entrée (m)",
  "Possible": "Possible",
  "Restricted": "Restreint",
  "Key Handover": "Remise des clés",
  "In Person": "En personne",
  "Mailbox": "Boîte aux lettres",
  "Neighbor": "Voisin",
  "Management": "Gérance",
  "Key Box": "Boîte à clés",
  "Schedule": "Calendrier",
  "Cleaning Date": "Date de nettoyage",
  "From *": "De *",
  "To *": "À *",
  "Express": "Express",
  "Re-cleaning after inspection": "Nouveau nettoyage après inspection",
  "Guarantee until handover": "Garantie jusqu'à la remise",
  "Disposal": "Élimination",
  "Moving combined": "Déménagement combiné",

  // Moving
  "Industrial": "Industriel",
  "Public": "Public",
  "Concrete": "Béton",
  "Epoxy": "Epoxy",
  "Rough": "Brut",
  "Fine": "Fin",
  "Intermediate": "Intermédiaire",
  "Handover": "Remise",
  "Project": "Projet",
  "Project Phase": "Phase du projet",
  "Phase": "Phase",
  "Skylights": "Puits de lumière",
  "Facade": "Façade",
  "Paint Spoils": "Taches de peinture",
  "Stickers": "Autocollants",
  "Cement": "Ciment",
  "Glue": "Colle",
  "Dust": "Poussière",
  "Silicone": "Silicone",
  "Waste Disposal": "Élimination des déchets",
  "Container": "Conteneur",
  "High Pressure": "Haute pression",
  "Sealing": "Scellement",
  "On Site Context": "Contexte sur place",
  "Water": "Eau",
  "Electricity": "Électricité",
  "Deadline": "Délai",
  "Name Contact": "Nom du contact",

  "Hotel": "Hôtel",
  "Canteen": "Cantine",
  "Catering": "Restauration",
  "Take-away": "À emporter",
  "Cafe": "Café",
  "Bar": "Bar",
  "Takeaway": "À emporter",
  "Club": "Club",
  "Restrooms": "Toilettes",
  "Staff Restrooms": "Toilettes personnel",
  "Kitchen Details": "Détails de la cuisine",
  "Grease Traps": "Bacs à graisse",
  "Ovens": "Fours",
  "Deep Fryers": "Friteuses",
  "Cooling Units": "Appareils de refroidissement",
  "Drains": "Canalisations",
  "Walls": "Murs",
  "Dining Details": "Détails de la salle à manger",
  "Seating": "Sièges",
  "Restroom Details": "Détails des toilettes",
  "Urinals": "Urinoirs",
  "Stalls": "Cabines",
  "Sinks": "Lavabos",
  "Requirements": "Exigences",
  "Night": "Nuit",
  "Current Property": "Propriété actuelle",
  "Elevator Size": "Taille de l'ascenseur",
  "New Property": "Nouvelle propriété",
  "Property Size": "Taille de la propriété",
  "Floor Area": "Surface au sol",
  "Distance Parking": "Distance du parking",
  "Distance Details": "Détails de la distance",
  "Carrying Distance": "Distance de portage",
  "Stairs Info": "Info sur les escaliers",
  "Inventory": "Inventaire",
  "Boxes": "Cartons",
  "Furniture Details": "Détails des meubles",
  "Heavy Items": "Objets lourds",
  "Assembly Needed": "Montage nécessaire",
  "Pianos": "Pianos",
  "Safes": "Coffres-forts",
  "Special Care": "Soins particuliers",
  "Moving Details": "Détails du déménagement",
  "Move Date": "Date de déménagement",
  "Move Time": "Heure de déménagement",
  "Flexibility": "Flexibilité",
  "Timeframe": "Créneau horaire",
  "Additional Needs": "Besoins supplémentaires",
  "Packing Services": "Services d'emballage",
  "Unpacking Services": "Services de déballage",
  "Storage Needed": "Stockage nécessaire",
  "Special Requests": "Demandes spéciales",

  "Disposal Type": "Type de déchets",
  "Household Goods": "Biens ménagers",
  "Furniture": "Meubles",
  "Appliances": "Électroménager",
  "Electronics": "Électronique",
  "Green Waste": "Déchets verts",
  "Items & Volume": "Articles & Volume",
  "Location Type": "Type d'emplacement",
  "Additional Options": "Options supplémentaires",
  "Dismantling needed": "Démontage nécessaire",
  "Container provided": "Conteneur fourni",

  "Windows Title": "Fenêtres et vitrages",
  "Normal Windows": "Fenêtres normales (Nombre / m²)",
  "French Doors": "Portes-fenêtres",
  "Other Glass Surfaces": "Autres surfaces vitrées",
  "Panoramic Hint": "Vitrages panoramiques / Jardin d'hiver",
  "Blinds Title": "Stores / Ombrage",
  "Shutters": "Volets",
  "Slat": "Stores à lamelles",
  "Adjustable": "Stores réglables",
  "Blinds": "Stores / Volets roulants",
  "Other Special": "Autres (Veuillez préciser)",
  "No": "Non",
  "Special Features Title": "Particularités Fenêtres / Cadres",
  "Mold Frames": "Moisissures sur les cadres",
  "Small Casement": "Petits croisillons",
  "Roof Window": "Fenêtre de toit (accès difficile)",
  "Safety Film": "Films de sécurité / solaires",
  "No Special": "Aucune particularité",
  "Desired Cleaning Date": "Date de nettoyage souhaitée",
  "Delivery Handover Date": "Date de remise prévue",
  "Moving From": "Adresse de départ",
  "Current Living": "Logement actuel",
  "Studio": "Studio",
  "Elevator Available": "Ascenseur disponible?",
  "Yes": "Oui",
  "Current Living Space": "Surface habitable actuelle (m²)",
  "Moving To": "Adresse d'arrivée",
  "Storage": "Garde-meubles / Stockage",
  "New Elevator": "Nouvel ascenseur?",
  "New Living Space": "Nouvelle surface habitable (m²)",
  "People Moving": "Personnes dans le ménage",
  "People Moving Hint": "Nombre",
  "Moving Boxes": "Cartons de déménagement (estimation)",
  "Moving Boxes Hint": "Nombre de cartons",
  "Additional Supplies Title": "Matériel d'emballage supplémentaire requis?",
  "Moving Box": "Carton standard",
  "Wardrobe Box": "Penderie portable",
  "Bottle Carton": "Carton pour verres/bouteilles",
  "Adhesive Tape": "Ruban adhésif",
  "Cellar": "Cave",
  "Attic Screed": "Galetas / Grenier",
  "Garage Parking Space": "Garage / Place de parc",
  "Conservatory Balcony": "Jardin d'hiver / Balcon",
  "Stairs": "Escaliers",
  "Corridor": "Couloir",
  "Preferred Move Date": "Date de déménagement privilégiée",
  "Name First Name": "Nom et Prénom",
  "Company": "Entreprise",
  "Telephone Number": "Numéro de téléphone",
  "Parking Distance": "Distance du parking",

  "Label": "Fréquence / Intervalle",
  "Unique": "Une seule fois",
  "Every Other Week": "Toutes les deux semaines",
  "Several Times Week": "Plusieurs fois par semaine"
};

function translateObj(obj, dict) {
  if (typeof obj === 'string') {
    if (dict[obj] && dict[obj] !== obj) {
      return dict[obj];
    }
    return obj;
  }
  if (Array.isArray(obj)) {
    return obj.map(item => translateObj(item, dict));
  }
  if (typeof obj === 'object' && obj !== null) {
    const newObj = {};
    for (const key in obj) {
      newObj[key] = translateObj(obj[key], dict);
    }
    return newObj;
  }
  return obj;
}

const dePath = path.resolve(__dirname, 'messages/de.json');
const frPath = path.resolve(__dirname, 'messages/fr.json');

const deData = JSON.parse(fs.readFileSync(dePath, 'utf8'));
const frData = JSON.parse(fs.readFileSync(frPath, 'utf8'));

if (deData.serviceForm && deData.serviceForm.wizard) {
  deData.serviceForm.wizard = translateObj(deData.serviceForm.wizard, deDict);
}
if (frData.serviceForm && frData.serviceForm.wizard) {
  frData.serviceForm.wizard = translateObj(frData.serviceForm.wizard, frDict);
}

fs.writeFileSync(dePath, JSON.stringify(deData, null, 2));
fs.writeFileSync(frPath, JSON.stringify(frData, null, 2));
console.log('Translations updated successfully.');
